### ISSUE TITLE
If your update your profile you have to type password

### ISSUE THREAD

**Issue by waltherjochen** [prismacon/hone#7]
I wanted to update profile data without change password

![image](https://cloud.githubusercontent.com/assets/15231733/14636828/0656cf62-062e-11e6-8cda-3e3a4fd0d24f.png)

But there is this error message
![image](https://cloud.githubusercontent.com/assets/15231733/14636839/13f12a64-062e-11e6-8177-8688265fe30c.png)

**Comment by acorn489** [comment]
There is a "current password" field below it. You must enter your password to change any profile data.

The field you have referenced is used to change your current password.

**Comment by waltherjochen** [comment]
yes your right
